# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: build-branch
on:
  push:
env:
  FAIL_FAST: ${{ github.event_name == 'pull_request' }}
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
concurrency:
  group: ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  integration:
    runs-on: ubuntu-18.04
    timeout-minutes: 240
    steps:
      - name: Setup link to SSD
        run: sudo mkdir mnt && sudo mount --bind /mnt `pwd`/mnt && sudo chmod 777 mnt
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          path: mnt/ozone
      - name: Cache for maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('mnt/ozone/**/pom.xml') }}-8-integration
          restore-keys: |
            maven-repo-${{ hashFiles('mnt/ozone/**/pom.xml') }}-8
            maven-repo-${{ hashFiles('mnt/ozone/**/pom.xml') }}
            maven-repo-
      - name: Execute tests
        run: mnt/ozone/hadoop-ozone/dev-support/checks/integration.sh -Dtest='TestOzoneManagerConfiguration,TestOzoneFileInterfaces'
        env:
          ITERATIONS: 10
      - name: Summary of failures
        run: cat mnt/ozone/target/${{ github.job }}/summary.txt
        if: always()
      - name: Archive build results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: integration
          path: mnt/ozone/target/integration
        continue-on-error: true
      - name: Delete temporary build artifacts before caching
        run: |
          #Never cache local artifacts
          rm -rf ~/.m2/repository/org/apache/ozone/hdds*
          rm -rf ~/.m2/repository/org/apache/ozone/ozone*
        if: always()
